server:
  port: 8081

spring:
  # rabbitMQ config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # datasource config
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo_db"     #local app        -> (pgadmin4|postgres) local db |
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: garden
    hibernate:
      ddl-auto: update #(create-drop, update, create, validate)
    show-sql: false #true



rabbitmq:
  register:
    queue: register